import streamlit as st
import joblib
import numpy as np
import matplotlib.pyplot as plt
from fpdf import FPDF
import os
import gdown

# ------------------------
# PAGE CONFIG
# ------------------------
st.set_page_config(
    page_title="Student Performance Predictor",
    page_icon="🎓",
    layout="centered"
)

# ------------------------
# DARK PROFESSIONAL UI
# ------------------------
st.markdown("""
<style>

.stApp {
    background: linear-gradient(-45deg,
        #0b1220,
        #111827,
        #0f172a,
        #1e293b
    );
    background-size: 400% 400%;
    animation: moveBG 12s ease infinite;
}

@keyframes moveBG {
    0% {background-position: 0% 50%;}
    50% {background-position: 100% 50%;}
    100% {background-position: 0% 50%;}
}

/* Glass effect */
.block-container {
    background: rgba(255,255,255,0.04);
    padding: 2rem;
    border-radius: 20px;
    backdrop-filter: blur(14px);
    box-shadow: 0px 10px 30px rgba(0,0,0,0.6);
    color: white;
}

h1, h2, h3 {
    color: white;
}

label {
    color: #cbd5e1 !important;
}

/* Button */
div.stButton > button {
    background-color: #3b82f6;
    color: white;
    border-radius: 12px;
    height: 50px;
    font-size: 16px;
}
div.stButton > button:hover {
    background-color: #2563eb;
}

/* PDF button */
div.stDownloadButton > button {
    background: linear-gradient(90deg, #ff4b91, #ff1744);
    color: white;
    border-radius: 14px;
    height: 55px;
    font-size: 15px;
    font-weight: bold;
}

</style>
""", unsafe_allow_html=True)

# ------------------------
# LOAD MODEL FROM GOOGLE DRIVE (SAFE FOR DEPLOY)
# ------------------------

file_id = "1CexcQtsejo5TEsP8X_WOzn794GGB8_e5"
url = f"https://drive.google.com/uc?id={file_id}"
output = "dropout_model.pkl"

if not os.path.exists(output):
    with st.spinner("Loading AI Model..."):
        gdown.download(url, output, quiet=False)

model = joblib.load(output)

# ------------------------
# TITLE
# ------------------------
st.title("🎓 Student Performance Prediction System")

st.write("""
Machine Learning system to predict:
Graduation, Enrollment or Dropout
""")

st.markdown("---")

# ------------------------
# INPUTS
# ------------------------

age = st.number_input("Age at Enrollment", 17, 70, 20)
admission_grade = st.number_input("University Admission Score", 0.0, 200.0, 120.0)
previous_grade = st.number_input("Previous Academic Score", 0.0, 200.0, 120.0)

tuition = st.selectbox("Tuition Fees Status", ["Yes", "No"])

occupation_dict = {
    "Teacher": 1,
    "Engineer": 2,
    "Doctor": 3,
    "Business": 4,
    "Government Employee": 5,
    "Private Employee": 6,
    "Self Employed": 7,
    "Unemployed": 8
}

father_job = st.selectbox("Father's Occupation", list(occupation_dict.keys()))
mother_job = st.selectbox("Mother's Occupation", list(occupation_dict.keys()))

st.subheader("Academic Performance")

first_approved = st.number_input("Courses Passed (Semester 1)", 0, 20, 5)
first_grade = st.number_input("Average Grade (Semester 1)", 0.0, 20.0, 10.0)

second_approved = st.number_input("Courses Passed (Semester 2)", 0, 20, 5)
second_grade = st.number_input("Average Grade (Semester 2)", 0.0, 20.0, 10.0)

# ------------------------
# PDF FUNCTION
# ------------------------
def generate_pdf(result_text, grad, enrolled, dropout):
    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Arial", "B", 18)
    pdf.cell(200, 10, "STUDENT PERFORMANCE REPORT", ln=True, align="C")

    pdf.ln(10)

    pdf.set_font("Arial", "", 12)
    pdf.cell(200, 8, f"Result: {result_text}", ln=True)

    pdf.ln(5)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(200, 10, "Probability Analysis", ln=True)

    pdf.set_font("Arial", "", 12)
    pdf.cell(200, 8, f"Graduate: {grad:.2f}%", ln=True)
    pdf.cell(200, 8, f"Enrolled: {enrolled:.2f}%", ln=True)
    pdf.cell(200, 8, f"Dropout: {dropout:.2f}%", ln=True)

    pdf.ln(10)

    pdf.set_font("Arial", "I", 10)
    pdf.cell(200, 10, "Generated by AI System", ln=True, align="C")

    file_name = "student_report.pdf"
    pdf.output(file_name)

    return file_name

# ------------------------
# PREDICTION
# ------------------------

if st.button("🔮 Generate Prediction"):

    sample = np.zeros((1, 36))

    sample[0][19] = age
    sample[0][12] = admission_grade
    sample[0][6] = previous_grade
    sample[0][16] = 1 if tuition == "Yes" else 0
    sample[0][11] = occupation_dict[father_job]
    sample[0][10] = occupation_dict[mother_job]
    sample[0][24] = first_approved
    sample[0][25] = first_grade
    sample[0][30] = second_approved
    sample[0][31] = second_grade

    prediction = model.predict(sample)
    probabilities = model.predict_proba(sample)

    dropout_prob = probabilities[0][0] * 100
    enrolled_prob = probabilities[0][1] * 100
    graduate_prob = probabilities[0][2] * 100

    st.markdown("---")
    st.subheader("📊 Prediction Result")

    if prediction[0] == 0:
        result_text = "High Dropout Risk"
        st.error("⚠️ High Dropout Risk")

    elif prediction[0] == 1:
        result_text = "Likely to Remain Enrolled"
        st.warning("📚 Likely to Remain Enrolled")

    else:
        result_text = "Likely to Graduate"
        st.success("🎓 Likely to Graduate")

    st.subheader("📈 Confidence Level")

    st.write("Graduate Probability")
    st.progress(int(graduate_prob))
    st.write(f"{graduate_prob:.2f}%")

    st.write("Enrolled Probability")
    st.progress(int(enrolled_prob))
    st.write(f"{enrolled_prob:.2f}%")

    st.write("Dropout Probability")
    st.progress(int(dropout_prob))
    st.write(f"{dropout_prob:.2f}%")

    st.subheader("📊 Visualization")

    labels = ["Dropout", "Enrolled", "Graduate"]
    values = [dropout_prob, enrolled_prob, graduate_prob]

    fig, ax = plt.subplots()
    ax.bar(labels, values)
    st.pyplot(fig)

    fig2, ax2 = plt.subplots()
    ax2.pie(values, labels=labels, autopct="%1.1f%%")
    st.pyplot(fig2)

    pdf_file = generate_pdf(result_text, graduate_prob, enrolled_prob, dropout_prob)

    with open(pdf_file, "rb") as f:
        st.download_button(
            "💖 Download AI Report Card PDF",
            f,
            file_name="AI_Report_Card.pdf"
        )